apiVersion: v1
kind: Service
metadata:
  name: minio-svc-address
spec:
  ports:
    -
      nodePort: 32000
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio
  type: NodePort
