apiVersion: v1
kind: Service
metadata:
  name: minio-svc-console-address
spec:
  ports:
    -
      nodePort: 31000
      port: 31000
      protocol: TCP
      targetPort: 31000
  selector:
    app: minio
  type: NodePort
